export const movies = [
  {
    id: 1,
    title: "Inception",
    description: "A thief enters dreams to steal secrets.",
    year: 2010,
    genre: "Science Fiction",
    director: "Christopher Nolan",
    actors: ["Leonardo DiCaprio", "Tom Hardy"],
    image: "https://www.hollywoodinsider.com/wp-content/uploads/2020/01/Hollywood-Insider-Feature-Inception-Greatest-Movie-Of-The-Decade-Leonardo-Dicaprio-Tom-Hardy-Marion-Cotillard-Joseph-Gordon-Levitt-Michael-Caine-Christopher-Nolan-Ken-Wantanabe-Ellen-Paige.jpg",
    trailer: "https://www.youtube.com/embed/YoHD9XEInc0",
    rating: 5
  },
  {
    id: 2,
    title: "Spider-Man",
    description: "A young man gains spider powers.",
    year: 2002,
    genre: "Action",
    director: "Sam Raimi",
    actors: ["Tobey Maguire", "Kirsten Dunst"],
    image: "https://fr.web.img2.acsta.net/pictures/23/05/11/10/00/1986933.jpg",
    trailer: "https://www.youtube.com/embed/t06RUxPbp_c",
    rating: 4
  },
  {
    id: 3,
    title: "The Dark Knight",
    description: "Batman faces the Joker.",
    year: 2008,
    genre: "Action",
    director: "Christopher Nolan",
    actors: ["Christian Bale", "Heath Ledger"],
    image: "https://play-lh.googleusercontent.com/auIs5tjWlLYaFPGClZOJ7m5YVbnX6uBvz0X02r8TkwFKdzE53ww2MqWSS9gU0YNqoYwvpg",
    trailer: "https://www.youtube.com/embed/EXeTwQWrcwY",
    rating: 5
  },
  {
    id: 4,
    title: "Avengers: Endgame",
    description: "Heroes unite to save the universe.",
    year: 2019,
    genre: "Action",
    director: "Russo Brothers",
    actors: ["Robert Downey Jr.", "Chris Evans"],
    image: "https://fr.web.img2.acsta.net/pictures/19/04/04/09/04/0472053.jpg",
    trailer: "https://www.youtube.com/embed/TcMBFSGVi1c",
    rating: 4
  },
  {
    id: 5,
    title: "Joker",
    description: "Origin story of the Joker.",
    year: 2019,
    genre: "Drama",
    director: "Todd Phillips",
    actors: ["Joaquin Phoenix"],
    image: "https://play-lh.googleusercontent.com/Wi2UwqsUCS3heo5-VYLI2v12zbiXKHJWih8ZCSrQzjxZA5PR8MFWVjcupL4hFekawjGst_sBsEF_ECdLkQ",
    trailer: "https://www.youtube.com/embed/zAGVQLHvwOY",
    rating: 4
  },
  {
    id: 6,
    title: "Interstellar",
    description: "Space exploration to save humanity.",
    year: 2014,
    genre: "Sci-Fi",
    director: "Christopher Nolan",
    actors: ["Matthew McConaughey"],
    image: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10543523_p_v8_as.jpg",
    trailer: "https://www.youtube.com/embed/zSWdZVtXT7E",
    rating: 5
  },
  {
    id: 7,
    title: "Batman",
    description: "The dark knight protects Gotham.",
    year: 1993,
    genre: "Action",
    director: "Eric Radomski",
    actors: ["Kevin Conroy"],
    image: "https://upload.wikimedia.org/wikipedia/en/e/ea/Batman_mask_of_the_phantasm_poster.jpg",
    trailer: "https://www.youtube.com/embed/rrmUk2YUm14",
    rating: 4
  },
  {
    id: 8,
    title: "Superman",
    description: "Man of steel saves the world.",
    year: 2013,
    genre: "Action",
    director: "Zack Snyder",
    actors: ["Henry Cavill"],
    image: "https://fr.web.img2.acsta.net/img/97/ca/97ca64f4e5790703d0358c61aa7d1a11.jpg",
    trailer: "https://www.youtube.com/embed/T6DJcgm3wNY",
    rating: 3
  },
  {
    id: 9,
    title: "The Matrix",
    description: "A hacker discovers reality is fake.",
    year: 1999,
    genre: "Sci-Fi",
    director: "Wachowski Sisters",
    actors: ["Keanu Reeves"],
    image: "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_.jpg",
    trailer: "https://www.youtube.com/embed/vKQi3bBA1y8",
    rating: 5
  },
  {
    id: 10,
    title: "Shrek",
    description: "An ogre saves a princess.",
    year: 2001,
    genre: "Animation",
    director: "Andrew Adamson",
    actors: ["Mike Myers"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpLC8JnI3bxmGQSJ_9SItneou-yrJ8XIdWgA&s",
    trailer: "https://www.youtube.com/embed/CwXOrWvPBPk",
    rating: 4
  },
  {
    id: 11,
    title: "Gladiator",
    description: "A general seeks revenge.",
    year: 2000,
    genre: "Drama",
    director: "Ridley Scott",
    actors: ["Russell Crowe"],
    image: "https://m.media-amazon.com/images/M/MV5BYWQ4YmNjYjEtOWE1Zi00Y2U4LWI4NTAtMTU0MjkxNWQ1ZmJiXkEyXkFqcGc@._V1_.jpg",
    trailer: "https://www.youtube.com/embed/owK1qxDselE",
    rating: 5
  },
  {
    id: 12,
    title: "Fast & Furious",
    description: "Street racing action.",
    year: 2001,
    genre: "Action",
    director: "Rob Cohen",
    actors: ["Vin Diesel"],
    image: "https://upload.wikimedia.org/wikipedia/en/8/8f/Fast_and_Furious_Poster.jpg",
    trailer: "https://www.youtube.com/embed/2TAOizOnNPo",
    rating: 3
  },
  {
    id: 13,
    title: "Harry Potter",
    description: "A wizard's journey.",
    year: 2001,
    genre: "Fantasy",
    director: "Chris Columbus",
    actors: ["Daniel Radcliffe"],
    image: "https://m.media-amazon.com/images/M/MV5BNTU1MzgyMDMtMzBlZS00YzczLThmYWEtMjU3YmFlOWEyMjE1XkEyXkFqcGc@._V1_.jpg",
    trailer: "https://www.youtube.com/embed/VyHV0BRtdxo",
    rating: 5
  },
  {
    id: 14,
    title: "Lord of the Rings",
    description: "Epic fantasy adventure.",
    year: 2001,
    genre: "Fantasy",
    director: "Peter Jackson",
    actors: ["Elijah Wood"],
    image: "https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_.jpg",
    trailer: "https://www.youtube.com/embed/V75dMMIW2B4",
    rating: 5
  },
  {
    id: 15,
    title: "Coco",
    description: "A boy travels to the land of the dead.",
    year: 2017,
    genre: "Animation",
    director: "Lee Unkrich",
    actors: ["Anthony Gonzalez"],
    image: "https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg",
    trailer: "https://www.youtube.com/embed/Rvr68u6k5sI",
    rating: 4
  }
];